/**:
  ros__parameters:
    filter_target_label:
      UNKNOWN : false  #wheeltec
      CAR : false
      TRUCK : false
      BUS : false
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false
