/**:
  ros__parameters:
    ld_velocity_ratio: 2.4    #wheeltec
    ld_lateral_error_ratio: 0.6
    ld_curvature_ratio: 120.0
    long_ld_lateral_error_threshold: 0.5
    min_lookahead_distance: 1.0
    max_lookahead_distance: 1.5
    converged_steer_rad: 0.40  #wheeltec
    reverse_min_lookahead_distance: 7.0
    prediction_ds: 0.5
    prediction_distance_length: 10.0
    resampling_ds: 0.1
    curvature_calculation_distance: 0.5    #wheeltec
    enable_path_smoothing: false
    path_filter_moving_ave_num: 25
