/**:
  ros__parameters:
    additional_lidars: []
    ransac_input_topics: []
    use_single_frame_filter: False   #wheeltec
    use_time_series_filter: False

    common_crop_box_filter:
      parameters:
        min_x: -100.0
        max_x: 150.0
        min_y: -70.0
        max_y: 70.0
        margin_max_z: 10.0  # to extend the crop box max_z from vehicle_height wheeltec
        margin_min_z: -10.0 # to extend the crop box min_z from ground wheeltec
        negative: False

    common_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0     #wheeltec
        local_slope_max_angle_deg: 5.0 # wheeltec recommended 30.0 for non elevation_grid_mode
        split_points_distance_tolerance: 1.0
        use_virtual_ground_point: True
        split_height_distance: 0.1     #wheeltec
        non_ground_height_threshold: 0.1      #wheeltec
        grid_size_m: 0.1
        grid_mode_switch_radius: 20.0
        gnd_grid_buffer_size: 4
        detection_range_z_max: 2.5
        elevation_grid_mode: true
        use_recheck_ground_cluster: true
        low_priority_region_x: -20.0
        center_pcl_shift: 0.0
        radial_divider_angle_deg: 1.0
